blank_issues_enabled: false
contact_links:
  - name: Bug report
    about: Create a bug report
  - name: Feature request
    about: Suggest an idea for this project
  - name: Enhancement
    about: Get benefit yyy, via building xxx
  - name: Report a security vulnerability
    about: Please review our security policy for more details.
